# Temp directories until other Techpacks are completed
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/ctum/5min

mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir1
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir2
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir3
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir4
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir5
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir6
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir7
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir8
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir9
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir10
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir11
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir12
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir13
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir14
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir15
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir16
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir17
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir18
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir19
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir20
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir21
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir22
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir23
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir24
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir25
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir26
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir27
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir28
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir29
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir30
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir31
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir32
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir33
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir34
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir35
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir36
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir37
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir38
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir39
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir40
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir41
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir42
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir43
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir44
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir45
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir46
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir47
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir48
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir49
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_1/dir50

mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir1
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir2
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir3
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir4
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir5
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir6
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir7
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir8
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir9
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir10
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir11
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir12
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir13
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir14
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir15
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir16
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir17
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir18
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir19
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir20
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir21
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir22
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir23
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir24
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir25
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir26
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir27
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir28
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir29
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir30
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir31
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir32
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir33
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir34
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir35
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir36
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir37
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir38
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir39
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir40
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir41
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir42
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir43
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir44
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir45
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir46
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir47
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir48
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir49
mkdir -p /eniq/data/pmdata/eventdata/00/CTRS/lte_cfa/5min/events_oss_2/dir50

mkdir -p /eniq/data/etldata_/00/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/01/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/02/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/03/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/04/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/05/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/06/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/07/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/08/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/09/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/10/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/11/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/12/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/13/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/14/event_e_lte_hfa_err/raw/1/
mkdir -p /eniq/data/etldata_/15/event_e_lte_hfa_err/raw/1/

mkdir -p /eniq/data/etldata_/00/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/01/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/02/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/03/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/04/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/05/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/06/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/07/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/08/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/09/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/10/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/11/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/12/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/13/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/14/event_e_lte_hfa_array_erab_err/raw/1/
mkdir -p /eniq/data/etldata_/15/event_e_lte_hfa_array_erab_err/raw/1/